// Mock data for the CamCCUL website prototype.
// All placeholder values are wrapped in square brackets and are intended to be
// obviously fake — CamCCUL staff must replace them with real institutional data
// before launch. Affiliate names are systematically generated (not real credit
// union names) to demonstrate the directory layout at production scale.
// NOTE: the regional distribution below sums to 216 affiliates, not 220 — the
// per-region counts as specified add up to 216.
//
// Per-affiliate fields (city/address/phone/email) are intentionally left as
// English placeholder brackets rather than translated — with 216 systematically
// generated entries all sharing the same "[City Name]"-style filler, a
// bilingual duplicate of identical placeholder text adds no value and will be
// replaced wholesale once CamCCUL provides real affiliate data. Structural/UI
// text and genuinely distinct content (milestones, leadership, news,
// resources, services) are fully bilingual below.

import type { LocalizedText } from "./i18n";

export interface Affiliate {
  id: string;
  code: string;
  name: string;
  region: string;
  city: string;
  address: string;
  phone: string;
  email: string;
  isActive: boolean;
}

export interface ContactInfo {
  address: string;
  phone: string;
  email: string;
  officeHours: LocalizedText;
}

export interface LeadershipMember {
  name: LocalizedText;
  title: LocalizedText;
  bio: LocalizedText;
}

export interface NewsArticle {
  id: string;
  title: LocalizedText;
  slug: string;
  category: string;
  excerpt: LocalizedText;
  content: LocalizedText;
  publishedAt: string;
  imageUrl: string;
}

export interface Resource {
  id: string;
  title: LocalizedText;
  description: LocalizedText;
  category: string;
  fileType: string;
  fileSize: number;
  downloadCount: number;
}

export interface Service {
  icon: string;
  title: string;
  description: string;
  href: string;
}

export interface Milestone {
  year: string;
  title: LocalizedText;
  description: LocalizedText;
}

// Canonical region identifiers used for filtering, URL query params, and
// matching against Affiliate.region — never render these directly; look up
// the display label for the active language via `regionLabels` instead.
export const regions: string[] = [
  "ADAMAWA",
  "CENTRE",
  "EAST",
  "FAR NORTH",
  "LITTORAL",
  "NORTH",
  "NORTHWEST",
  "SOUTH",
  "SOUTHWEST",
  "WEST",
];

export const regionLabels: Record<string, LocalizedText> = {
  ADAMAWA: { en: "Adamawa", fr: "Adamaoua" },
  CENTRE: { en: "Centre", fr: "Centre" },
  EAST: { en: "East", fr: "Est" },
  "FAR NORTH": { en: "Far North", fr: "Extrême-Nord" },
  LITTORAL: { en: "Littoral", fr: "Littoral" },
  NORTH: { en: "North", fr: "Nord" },
  NORTHWEST: { en: "Northwest", fr: "Nord-Ouest" },
  SOUTH: { en: "South", fr: "Sud" },
  SOUTHWEST: { en: "Southwest", fr: "Sud-Ouest" },
  WEST: { en: "West", fr: "Ouest" },
};

// Canonical NewsArticle.category values used for filtering — look up the
// display label for the active language via `newsCategoryLabels` instead of
// rendering the raw value.
export const newsCategoryLabels: Record<string, LocalizedText> = {
  All: { en: "All", fr: "Toutes" },
  Circular: { en: "Circular", fr: "Circulaire" },
  Training: { en: "Training", fr: "Formation" },
  COBAC: { en: "COBAC", fr: "COBAC" },
  Announcement: { en: "Announcement", fr: "Annonce" },
  Event: { en: "Event", fr: "Événement" },
};

export const affiliates: Affiliate[] = [
  {
    id: "nw-001",
    code: "NW-001",
    name: "Affiliate Credit Union NW-001",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-002",
    code: "NW-002",
    name: "Affiliate Savings & Credit NW-002",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-003",
    code: "NW-003",
    name: "Affiliate Community CU NW-003",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-004",
    code: "NW-004",
    name: "Affiliate Cooperative Credit NW-004",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-005",
    code: "NW-005",
    name: "Affiliate Rural Credit Union NW-005",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-006",
    code: "NW-006",
    name: "Affiliate Savings Cooperative NW-006",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-007",
    code: "NW-007",
    name: "Affiliate Community Credit Union NW-007",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-008",
    code: "NW-008",
    name: "Affiliate Cooperative Savings NW-008",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-009",
    code: "NW-009",
    name: "Affiliate Credit Union NW-009",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-010",
    code: "NW-010",
    name: "Affiliate Savings & Credit NW-010",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-011",
    code: "NW-011",
    name: "Affiliate Community CU NW-011",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-012",
    code: "NW-012",
    name: "Affiliate Cooperative Credit NW-012",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-013",
    code: "NW-013",
    name: "Affiliate Rural Credit Union NW-013",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-014",
    code: "NW-014",
    name: "Affiliate Savings Cooperative NW-014",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-015",
    code: "NW-015",
    name: "Affiliate Community Credit Union NW-015",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-016",
    code: "NW-016",
    name: "Affiliate Cooperative Savings NW-016",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-017",
    code: "NW-017",
    name: "Affiliate Credit Union NW-017",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-018",
    code: "NW-018",
    name: "Affiliate Savings & Credit NW-018",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-019",
    code: "NW-019",
    name: "Affiliate Community CU NW-019",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-020",
    code: "NW-020",
    name: "Affiliate Cooperative Credit NW-020",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-021",
    code: "NW-021",
    name: "Affiliate Rural Credit Union NW-021",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-022",
    code: "NW-022",
    name: "Affiliate Savings Cooperative NW-022",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-023",
    code: "NW-023",
    name: "Affiliate Community Credit Union NW-023",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-024",
    code: "NW-024",
    name: "Affiliate Cooperative Savings NW-024",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-025",
    code: "NW-025",
    name: "Affiliate Credit Union NW-025",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-026",
    code: "NW-026",
    name: "Affiliate Savings & Credit NW-026",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-027",
    code: "NW-027",
    name: "Affiliate Community CU NW-027",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-028",
    code: "NW-028",
    name: "Affiliate Cooperative Credit NW-028",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-029",
    code: "NW-029",
    name: "Affiliate Rural Credit Union NW-029",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-030",
    code: "NW-030",
    name: "Affiliate Savings Cooperative NW-030",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-031",
    code: "NW-031",
    name: "Affiliate Community Credit Union NW-031",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-032",
    code: "NW-032",
    name: "Affiliate Cooperative Savings NW-032",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-033",
    code: "NW-033",
    name: "Affiliate Credit Union NW-033",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-034",
    code: "NW-034",
    name: "Affiliate Savings & Credit NW-034",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-035",
    code: "NW-035",
    name: "Affiliate Community CU NW-035",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-036",
    code: "NW-036",
    name: "Affiliate Cooperative Credit NW-036",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-037",
    code: "NW-037",
    name: "Affiliate Rural Credit Union NW-037",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-038",
    code: "NW-038",
    name: "Affiliate Savings Cooperative NW-038",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-039",
    code: "NW-039",
    name: "Affiliate Community Credit Union NW-039",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-040",
    code: "NW-040",
    name: "Affiliate Cooperative Savings NW-040",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-041",
    code: "NW-041",
    name: "Affiliate Credit Union NW-041",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "nw-042",
    code: "NW-042",
    name: "Affiliate Savings & Credit NW-042",
    region: "NORTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-001",
    code: "LT-001",
    name: "Affiliate Community CU LT-001",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-002",
    code: "LT-002",
    name: "Affiliate Cooperative Credit LT-002",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-003",
    code: "LT-003",
    name: "Affiliate Rural Credit Union LT-003",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-004",
    code: "LT-004",
    name: "Affiliate Savings Cooperative LT-004",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-005",
    code: "LT-005",
    name: "Affiliate Community Credit Union LT-005",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-006",
    code: "LT-006",
    name: "Affiliate Cooperative Savings LT-006",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-007",
    code: "LT-007",
    name: "Affiliate Credit Union LT-007",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-008",
    code: "LT-008",
    name: "Affiliate Savings & Credit LT-008",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-009",
    code: "LT-009",
    name: "Affiliate Community CU LT-009",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-010",
    code: "LT-010",
    name: "Affiliate Cooperative Credit LT-010",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-011",
    code: "LT-011",
    name: "Affiliate Rural Credit Union LT-011",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-012",
    code: "LT-012",
    name: "Affiliate Savings Cooperative LT-012",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-013",
    code: "LT-013",
    name: "Affiliate Community Credit Union LT-013",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-014",
    code: "LT-014",
    name: "Affiliate Cooperative Savings LT-014",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-015",
    code: "LT-015",
    name: "Affiliate Credit Union LT-015",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-016",
    code: "LT-016",
    name: "Affiliate Savings & Credit LT-016",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-017",
    code: "LT-017",
    name: "Affiliate Community CU LT-017",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-018",
    code: "LT-018",
    name: "Affiliate Cooperative Credit LT-018",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-019",
    code: "LT-019",
    name: "Affiliate Rural Credit Union LT-019",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-020",
    code: "LT-020",
    name: "Affiliate Savings Cooperative LT-020",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-021",
    code: "LT-021",
    name: "Affiliate Community Credit Union LT-021",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-022",
    code: "LT-022",
    name: "Affiliate Cooperative Savings LT-022",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-023",
    code: "LT-023",
    name: "Affiliate Credit Union LT-023",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-024",
    code: "LT-024",
    name: "Affiliate Savings & Credit LT-024",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-025",
    code: "LT-025",
    name: "Affiliate Community CU LT-025",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-026",
    code: "LT-026",
    name: "Affiliate Cooperative Credit LT-026",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-027",
    code: "LT-027",
    name: "Affiliate Rural Credit Union LT-027",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-028",
    code: "LT-028",
    name: "Affiliate Savings Cooperative LT-028",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-029",
    code: "LT-029",
    name: "Affiliate Community Credit Union LT-029",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-030",
    code: "LT-030",
    name: "Affiliate Cooperative Savings LT-030",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-031",
    code: "LT-031",
    name: "Affiliate Credit Union LT-031",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-032",
    code: "LT-032",
    name: "Affiliate Savings & Credit LT-032",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-033",
    code: "LT-033",
    name: "Affiliate Community CU LT-033",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-034",
    code: "LT-034",
    name: "Affiliate Cooperative Credit LT-034",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "lt-035",
    code: "LT-035",
    name: "Affiliate Rural Credit Union LT-035",
    region: "LITTORAL",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-001",
    code: "CE-001",
    name: "Affiliate Savings Cooperative CE-001",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-002",
    code: "CE-002",
    name: "Affiliate Community Credit Union CE-002",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-003",
    code: "CE-003",
    name: "Affiliate Cooperative Savings CE-003",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-004",
    code: "CE-004",
    name: "Affiliate Credit Union CE-004",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-005",
    code: "CE-005",
    name: "Affiliate Savings & Credit CE-005",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-006",
    code: "CE-006",
    name: "Affiliate Community CU CE-006",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-007",
    code: "CE-007",
    name: "Affiliate Cooperative Credit CE-007",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-008",
    code: "CE-008",
    name: "Affiliate Rural Credit Union CE-008",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-009",
    code: "CE-009",
    name: "Affiliate Savings Cooperative CE-009",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-010",
    code: "CE-010",
    name: "Affiliate Community Credit Union CE-010",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-011",
    code: "CE-011",
    name: "Affiliate Cooperative Savings CE-011",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-012",
    code: "CE-012",
    name: "Affiliate Credit Union CE-012",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-013",
    code: "CE-013",
    name: "Affiliate Savings & Credit CE-013",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-014",
    code: "CE-014",
    name: "Affiliate Community CU CE-014",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-015",
    code: "CE-015",
    name: "Affiliate Cooperative Credit CE-015",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-016",
    code: "CE-016",
    name: "Affiliate Rural Credit Union CE-016",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-017",
    code: "CE-017",
    name: "Affiliate Savings Cooperative CE-017",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-018",
    code: "CE-018",
    name: "Affiliate Community Credit Union CE-018",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-019",
    code: "CE-019",
    name: "Affiliate Cooperative Savings CE-019",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-020",
    code: "CE-020",
    name: "Affiliate Credit Union CE-020",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-021",
    code: "CE-021",
    name: "Affiliate Savings & Credit CE-021",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-022",
    code: "CE-022",
    name: "Affiliate Community CU CE-022",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-023",
    code: "CE-023",
    name: "Affiliate Cooperative Credit CE-023",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-024",
    code: "CE-024",
    name: "Affiliate Rural Credit Union CE-024",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-025",
    code: "CE-025",
    name: "Affiliate Savings Cooperative CE-025",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-026",
    code: "CE-026",
    name: "Affiliate Community Credit Union CE-026",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-027",
    code: "CE-027",
    name: "Affiliate Cooperative Savings CE-027",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-028",
    code: "CE-028",
    name: "Affiliate Credit Union CE-028",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-029",
    code: "CE-029",
    name: "Affiliate Savings & Credit CE-029",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ce-030",
    code: "CE-030",
    name: "Affiliate Community CU CE-030",
    region: "CENTRE",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-001",
    code: "SW-001",
    name: "Affiliate Cooperative Credit SW-001",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-002",
    code: "SW-002",
    name: "Affiliate Rural Credit Union SW-002",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-003",
    code: "SW-003",
    name: "Affiliate Savings Cooperative SW-003",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-004",
    code: "SW-004",
    name: "Affiliate Community Credit Union SW-004",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-005",
    code: "SW-005",
    name: "Affiliate Cooperative Savings SW-005",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-006",
    code: "SW-006",
    name: "Affiliate Credit Union SW-006",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-007",
    code: "SW-007",
    name: "Affiliate Savings & Credit SW-007",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-008",
    code: "SW-008",
    name: "Affiliate Community CU SW-008",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-009",
    code: "SW-009",
    name: "Affiliate Cooperative Credit SW-009",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-010",
    code: "SW-010",
    name: "Affiliate Rural Credit Union SW-010",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-011",
    code: "SW-011",
    name: "Affiliate Savings Cooperative SW-011",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-012",
    code: "SW-012",
    name: "Affiliate Community Credit Union SW-012",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-013",
    code: "SW-013",
    name: "Affiliate Cooperative Savings SW-013",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-014",
    code: "SW-014",
    name: "Affiliate Credit Union SW-014",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-015",
    code: "SW-015",
    name: "Affiliate Savings & Credit SW-015",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-016",
    code: "SW-016",
    name: "Affiliate Community CU SW-016",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-017",
    code: "SW-017",
    name: "Affiliate Cooperative Credit SW-017",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-018",
    code: "SW-018",
    name: "Affiliate Rural Credit Union SW-018",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-019",
    code: "SW-019",
    name: "Affiliate Savings Cooperative SW-019",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-020",
    code: "SW-020",
    name: "Affiliate Community Credit Union SW-020",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-021",
    code: "SW-021",
    name: "Affiliate Cooperative Savings SW-021",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-022",
    code: "SW-022",
    name: "Affiliate Credit Union SW-022",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-023",
    code: "SW-023",
    name: "Affiliate Savings & Credit SW-023",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-024",
    code: "SW-024",
    name: "Affiliate Community CU SW-024",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "sw-025",
    code: "SW-025",
    name: "Affiliate Cooperative Credit SW-025",
    region: "SOUTHWEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-001",
    code: "WE-001",
    name: "Affiliate Rural Credit Union WE-001",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-002",
    code: "WE-002",
    name: "Affiliate Savings Cooperative WE-002",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-003",
    code: "WE-003",
    name: "Affiliate Community Credit Union WE-003",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-004",
    code: "WE-004",
    name: "Affiliate Cooperative Savings WE-004",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-005",
    code: "WE-005",
    name: "Affiliate Credit Union WE-005",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-006",
    code: "WE-006",
    name: "Affiliate Savings & Credit WE-006",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-007",
    code: "WE-007",
    name: "Affiliate Community CU WE-007",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-008",
    code: "WE-008",
    name: "Affiliate Cooperative Credit WE-008",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-009",
    code: "WE-009",
    name: "Affiliate Rural Credit Union WE-009",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-010",
    code: "WE-010",
    name: "Affiliate Savings Cooperative WE-010",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-011",
    code: "WE-011",
    name: "Affiliate Community Credit Union WE-011",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-012",
    code: "WE-012",
    name: "Affiliate Cooperative Savings WE-012",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-013",
    code: "WE-013",
    name: "Affiliate Credit Union WE-013",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-014",
    code: "WE-014",
    name: "Affiliate Savings & Credit WE-014",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-015",
    code: "WE-015",
    name: "Affiliate Community CU WE-015",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-016",
    code: "WE-016",
    name: "Affiliate Cooperative Credit WE-016",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-017",
    code: "WE-017",
    name: "Affiliate Rural Credit Union WE-017",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-018",
    code: "WE-018",
    name: "Affiliate Savings Cooperative WE-018",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-019",
    code: "WE-019",
    name: "Affiliate Community Credit Union WE-019",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-020",
    code: "WE-020",
    name: "Affiliate Cooperative Savings WE-020",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-021",
    code: "WE-021",
    name: "Affiliate Credit Union WE-021",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-022",
    code: "WE-022",
    name: "Affiliate Savings & Credit WE-022",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-023",
    code: "WE-023",
    name: "Affiliate Community CU WE-023",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-024",
    code: "WE-024",
    name: "Affiliate Cooperative Credit WE-024",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "we-025",
    code: "WE-025",
    name: "Affiliate Rural Credit Union WE-025",
    region: "WEST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-001",
    code: "AD-001",
    name: "Affiliate Savings Cooperative AD-001",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-002",
    code: "AD-002",
    name: "Affiliate Community Credit Union AD-002",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-003",
    code: "AD-003",
    name: "Affiliate Cooperative Savings AD-003",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-004",
    code: "AD-004",
    name: "Affiliate Credit Union AD-004",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-005",
    code: "AD-005",
    name: "Affiliate Savings & Credit AD-005",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-006",
    code: "AD-006",
    name: "Affiliate Community CU AD-006",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-007",
    code: "AD-007",
    name: "Affiliate Cooperative Credit AD-007",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-008",
    code: "AD-008",
    name: "Affiliate Rural Credit Union AD-008",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-009",
    code: "AD-009",
    name: "Affiliate Savings Cooperative AD-009",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-010",
    code: "AD-010",
    name: "Affiliate Community Credit Union AD-010",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-011",
    code: "AD-011",
    name: "Affiliate Cooperative Savings AD-011",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-012",
    code: "AD-012",
    name: "Affiliate Credit Union AD-012",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-013",
    code: "AD-013",
    name: "Affiliate Savings & Credit AD-013",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-014",
    code: "AD-014",
    name: "Affiliate Community CU AD-014",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ad-015",
    code: "AD-015",
    name: "Affiliate Cooperative Credit AD-015",
    region: "ADAMAWA",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-001",
    code: "NO-001",
    name: "Affiliate Rural Credit Union NO-001",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-002",
    code: "NO-002",
    name: "Affiliate Savings Cooperative NO-002",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-003",
    code: "NO-003",
    name: "Affiliate Community Credit Union NO-003",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-004",
    code: "NO-004",
    name: "Affiliate Cooperative Savings NO-004",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-005",
    code: "NO-005",
    name: "Affiliate Credit Union NO-005",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-006",
    code: "NO-006",
    name: "Affiliate Savings & Credit NO-006",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-007",
    code: "NO-007",
    name: "Affiliate Community CU NO-007",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-008",
    code: "NO-008",
    name: "Affiliate Cooperative Credit NO-008",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-009",
    code: "NO-009",
    name: "Affiliate Rural Credit Union NO-009",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-010",
    code: "NO-010",
    name: "Affiliate Savings Cooperative NO-010",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-011",
    code: "NO-011",
    name: "Affiliate Community Credit Union NO-011",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-012",
    code: "NO-012",
    name: "Affiliate Cooperative Savings NO-012",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "no-013",
    code: "NO-013",
    name: "Affiliate Credit Union NO-013",
    region: "NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-001",
    code: "FN-001",
    name: "Affiliate Savings & Credit FN-001",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-002",
    code: "FN-002",
    name: "Affiliate Community CU FN-002",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-003",
    code: "FN-003",
    name: "Affiliate Cooperative Credit FN-003",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-004",
    code: "FN-004",
    name: "Affiliate Rural Credit Union FN-004",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-005",
    code: "FN-005",
    name: "Affiliate Savings Cooperative FN-005",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-006",
    code: "FN-006",
    name: "Affiliate Community Credit Union FN-006",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-007",
    code: "FN-007",
    name: "Affiliate Cooperative Savings FN-007",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-008",
    code: "FN-008",
    name: "Affiliate Credit Union FN-008",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-009",
    code: "FN-009",
    name: "Affiliate Savings & Credit FN-009",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-010",
    code: "FN-010",
    name: "Affiliate Community CU FN-010",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-011",
    code: "FN-011",
    name: "Affiliate Cooperative Credit FN-011",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-012",
    code: "FN-012",
    name: "Affiliate Rural Credit Union FN-012",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "fn-013",
    code: "FN-013",
    name: "Affiliate Savings Cooperative FN-013",
    region: "FAR NORTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-001",
    code: "EA-001",
    name: "Affiliate Community Credit Union EA-001",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-002",
    code: "EA-002",
    name: "Affiliate Cooperative Savings EA-002",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-003",
    code: "EA-003",
    name: "Affiliate Credit Union EA-003",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-004",
    code: "EA-004",
    name: "Affiliate Savings & Credit EA-004",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-005",
    code: "EA-005",
    name: "Affiliate Community CU EA-005",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-006",
    code: "EA-006",
    name: "Affiliate Cooperative Credit EA-006",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-007",
    code: "EA-007",
    name: "Affiliate Rural Credit Union EA-007",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-008",
    code: "EA-008",
    name: "Affiliate Savings Cooperative EA-008",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-009",
    code: "EA-009",
    name: "Affiliate Community Credit Union EA-009",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "ea-010",
    code: "EA-010",
    name: "Affiliate Cooperative Savings EA-010",
    region: "EAST",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-001",
    code: "SO-001",
    name: "Affiliate Credit Union SO-001",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-002",
    code: "SO-002",
    name: "Affiliate Savings & Credit SO-002",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-003",
    code: "SO-003",
    name: "Affiliate Community CU SO-003",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-004",
    code: "SO-004",
    name: "Affiliate Cooperative Credit SO-004",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-005",
    code: "SO-005",
    name: "Affiliate Rural Credit Union SO-005",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-006",
    code: "SO-006",
    name: "Affiliate Savings Cooperative SO-006",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-007",
    code: "SO-007",
    name: "Affiliate Community Credit Union SO-007",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
  {
    id: "so-008",
    code: "SO-008",
    name: "Affiliate Cooperative Savings SO-008",
    region: "SOUTH",
    city: "[City Name]",
    address: "[Address to be provided]",
    phone: "[Phone to be provided]",
    email: "[Email to be provided]",
    isActive: true,
  },
];

export const contactInfo: ContactInfo = {
  address: "P.O. Box 2011, Bamenda, North West Region, Cameroon",
  phone: "(237) 233 44 57 66",
  email: "camccul@camccul.com",
  officeHours: {
    en: "[Office hours to be provided by CamCCUL]",
    fr: "[Heures d'ouverture à fournir par CamCCUL]",
  },
};

export const mission: LocalizedText = {
  en: "CamCCUL's mission statement will appear here. This placeholder text demonstrates the layout and formatting of the mission section. The official mission statement will be provided by the League's communications department.",
  fr: "L'énoncé de mission de CamCCUL apparaîtra ici. Ce texte provisoire illustre la mise en page de la section mission. L'énoncé officiel sera fourni par le service communication de la Ligue.",
};

export const vision: LocalizedText = {
  en: "CamCCUL's vision statement will appear here. This placeholder text demonstrates the layout and formatting of the vision section. The official vision statement will be provided by the League's communications department.",
  fr: "L'énoncé de vision de CamCCUL apparaîtra ici. Ce texte provisoire illustre la mise en page de la section vision. L'énoncé officiel sera fourni par le service communication de la Ligue.",
};

const LEADERSHIP_TITLE_PLACEHOLDER: LocalizedText = {
  en: "[Position Title — to be provided]",
  fr: "[Titre du poste — à fournir]",
};
const LEADERSHIP_BIO_PLACEHOLDER: LocalizedText = {
  en: "[Biography will be inserted here upon receipt from CamCCUL administration. This placeholder demonstrates the layout for leadership profile cards.]",
  fr: "[La biographie sera insérée ici dès réception par l'administration de CamCCUL. Ce texte provisoire illustre la mise en page des fiches de direction.]",
};

export const leadership: LeadershipMember[] = [
  {
    name: { en: "[Board Chair Name — to be provided]", fr: "[Nom du président du conseil — à fournir]" },
    title: LEADERSHIP_TITLE_PLACEHOLDER,
    bio: LEADERSHIP_BIO_PLACEHOLDER,
  },
  {
    name: { en: "[Executive Director Name — to be provided]", fr: "[Nom du directeur exécutif — à fournir]" },
    title: LEADERSHIP_TITLE_PLACEHOLDER,
    bio: LEADERSHIP_BIO_PLACEHOLDER,
  },
  {
    name: { en: "[Board Member Name — to be provided]", fr: "[Nom du membre du conseil — à fournir]" },
    title: LEADERSHIP_TITLE_PLACEHOLDER,
    bio: LEADERSHIP_BIO_PLACEHOLDER,
  },
  {
    name: { en: "[Director Name — to be provided]", fr: "[Nom du directeur — à fournir]" },
    title: LEADERSHIP_TITLE_PLACEHOLDER,
    bio: LEADERSHIP_BIO_PLACEHOLDER,
  },
  {
    name: { en: "[Board Member Name — to be provided]", fr: "[Nom du membre du conseil — à fournir]" },
    title: LEADERSHIP_TITLE_PLACEHOLDER,
    bio: LEADERSHIP_BIO_PLACEHOLDER,
  },
  {
    name: { en: "[Executive Name — to be provided]", fr: "[Nom du cadre dirigeant — à fournir]" },
    title: LEADERSHIP_TITLE_PLACEHOLDER,
    bio: LEADERSHIP_BIO_PLACEHOLDER,
  },
];

const NEWS_TITLE_PLACEHOLDER: LocalizedText = {
  en: "[News Article Title — to be provided by CamCCUL communications]",
  fr: "[Titre de l'article — à fournir par le service communication de CamCCUL]",
};
const NEWS_EXCERPT_PLACEHOLDER: LocalizedText = {
  en: "[Article excerpt will appear here. This placeholder demonstrates the two-line preview format for news articles. Real content to be provided by CamCCUL communications department.]",
  fr: "[L'extrait de l'article apparaîtra ici. Ce texte provisoire illustre le format d'aperçu sur deux lignes des actualités. Le contenu réel sera fourni par le service communication de CamCCUL.]",
};
const NEWS_CONTENT_PLACEHOLDER: LocalizedText = {
  en: "[Full article content will appear here. This placeholder demonstrates the article detail layout. Real circulars, announcements, and news content to be provided by CamCCUL staff for publication on the website.]",
  fr: "[Le contenu complet de l'article apparaîtra ici. Ce texte provisoire illustre la mise en page détaillée d'un article. Les circulaires, annonces et actualités réelles seront fournies par le personnel de CamCCUL pour publication sur le site.]",
};

export const newsArticles: NewsArticle[] = [
  {
    id: "news-1",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-1",
    category: "Circular",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-01",
    imageUrl: "",
  },
  {
    id: "news-2",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-2",
    category: "Training",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-02",
    imageUrl: "",
  },
  {
    id: "news-3",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-3",
    category: "COBAC",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-03",
    imageUrl: "",
  },
  {
    id: "news-4",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-4",
    category: "Announcement",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-04",
    imageUrl: "",
  },
  {
    id: "news-5",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-5",
    category: "Event",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-05",
    imageUrl: "",
  },
  {
    id: "news-6",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-6",
    category: "Circular",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-06",
    imageUrl: "",
  },
  {
    id: "news-7",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-7",
    category: "Training",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-07",
    imageUrl: "",
  },
  {
    id: "news-8",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-8",
    category: "COBAC",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-08",
    imageUrl: "",
  },
  {
    id: "news-9",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-9",
    category: "Announcement",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-09",
    imageUrl: "",
  },
  {
    id: "news-10",
    title: NEWS_TITLE_PLACEHOLDER,
    slug: "news-article-10",
    category: "Event",
    excerpt: NEWS_EXCERPT_PLACEHOLDER,
    content: NEWS_CONTENT_PLACEHOLDER,
    publishedAt: "2026-07-10",
    imageUrl: "",
  },
];

const RESOURCE_TITLE_PLACEHOLDER: LocalizedText = {
  en: "[Document Title — to be provided by CamCCUL]",
  fr: "[Titre du document — à fournir par CamCCUL]",
};
const RESOURCE_DESCRIPTION_PLACEHOLDER: LocalizedText = {
  en: "[Document description will appear here. This placeholder demonstrates how downloadable resources will be displayed. Actual document titles, descriptions, and files to be provided by CamCCUL.]",
  fr: "[La description du document apparaîtra ici. Ce texte provisoire illustre l'affichage des ressources téléchargeables. Les titres, descriptions et fichiers réels seront fournis par CamCCUL.]",
};

export const resources: Resource[] = [
  {
    id: "res-1",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "ReportingTemplate",
    fileType: "PDF",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-2",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "COBACRegulation",
    fileType: "XLSX",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-3",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "TrainingMaterial",
    fileType: "PDF",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-4",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "Form",
    fileType: "DOCX",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-5",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "ReportingTemplate",
    fileType: "PDF",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-6",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "COBACRegulation",
    fileType: "XLSX",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-7",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "TrainingMaterial",
    fileType: "PDF",
    fileSize: 0,
    downloadCount: 0,
  },
  {
    id: "res-8",
    title: RESOURCE_TITLE_PLACEHOLDER,
    description: RESOURCE_DESCRIPTION_PLACEHOLDER,
    category: "Form",
    fileType: "DOCX",
    fileSize: 0,
    downloadCount: 0,
  },
];

export const services: Service[] = [
  {
    icon: "Shield",
    title: "Regulatory Supervision",
    description: "As the apex supervisory body for cooperative credit unions in Cameroon, CamCCUL is responsible for ensuring that every affiliate operates in compliance with COBAC regulations and international best practices. Our supervision framework is designed to protect member deposits, maintain financial stability, and promote confidence in the cooperative financial sector.",
    href: "/services/regulatory-supervision",
  },
  {
    icon: "FileSearch",
    title: "Financial Auditing",
    description: "Financial auditing is the cornerstone of trust in the cooperative credit union movement. At CamCCUL, our audit team conducts thorough, independent examinations of every affiliate's financial statements, internal controls, and operational procedures. Our audits provide assurance to members, regulators, and partners that credit union funds are managed responsibly and transparently.",
    href: "/services/financial-auditing",
  },
  {
    icon: "GraduationCap",
    title: "Capacity Building",
    description: "CamCCUL offers robust capacity building training for its affiliate credit unions, equipping staff with essential skills and knowledge to manage their institutions effectively.",
    href: "/services/capacity-building",
  },
  {
    icon: "Network",
    title: "Digitalization of Credit Unions",
    description: "Spearheading the digitalization of our 220 affiliate credit unions, streamlining operations and enhancing service delivery through innovative technology.",
    href: "/services/digitalization",
  },
];

const MILESTONE_TITLE_PLACEHOLDER: LocalizedText = {
  en: "[Milestone title — to be provided by CamCCUL]",
  fr: "[Titre du jalon — à fournir par CamCCUL]",
};
const MILESTONE_SHORT_DESCRIPTION_PLACEHOLDER: LocalizedText = {
  en: "[Historical milestone description will appear here.]",
  fr: "[La description de ce jalon historique apparaîtra ici.]",
};

export const milestones: Milestone[] = [
  {
    year: "1968",
    title: MILESTONE_TITLE_PLACEHOLDER,
    description: {
      en: "[Historical milestone description will appear here. This placeholder demonstrates the timeline layout. Real CamCCUL history and key dates to be provided by the League.]",
      fr: "[La description de ce jalon historique apparaîtra ici. Ce texte provisoire illustre la mise en page de la chronologie. L'historique réel et les dates clés seront fournis par la Ligue.]",
    },
  },
  {
    year: "1970s",
    title: MILESTONE_TITLE_PLACEHOLDER,
    description: MILESTONE_SHORT_DESCRIPTION_PLACEHOLDER,
  },
  {
    year: "1990s",
    title: MILESTONE_TITLE_PLACEHOLDER,
    description: MILESTONE_SHORT_DESCRIPTION_PLACEHOLDER,
  },
  {
    year: "2000s",
    title: MILESTONE_TITLE_PLACEHOLDER,
    description: MILESTONE_SHORT_DESCRIPTION_PLACEHOLDER,
  },
  {
    year: "2010s",
    title: MILESTONE_TITLE_PLACEHOLDER,
    description: MILESTONE_SHORT_DESCRIPTION_PLACEHOLDER,
  },
  {
    year: "Present",
    title: MILESTONE_TITLE_PLACEHOLDER,
    description: MILESTONE_SHORT_DESCRIPTION_PLACEHOLDER,
  },
];
